# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation.

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default!
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by default!
# ENABLE_LINTERS:

DISABLE_LINTERS:
  # TODO Find a good way to have fully consistent spell checking between VSC & CI
  - SPELL_CSPELL

# Keep this in sync with ignorePaths in .cspell.json
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: (\.github\|\.vscode)

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# TODO Enable this (but it will likely require some more work) - at least once, then disable again? (Because it won't be constantly needed, once it's clean.)
# VALIDATE_ALL_CODEBASE: true
