name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Thanks for stopping by here, and welcome! Someone will hopefully comment soon."
        pr-message: "Hello there! Welcome, and Thank You so much for contributing; Someone will hopefully review this Pull Request (PR) soon."
